server:
  port: 8081

spring:
  application:
    name: SHIRO2302
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_my_02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  type-aliases-package: com.qianfeng.day0818_tryshiro.pojo
  mapper-locations: mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true